### ISSUE TITLE
Make the app run on the domain root.

### ISSUE THREAD

**Issue by budhajeewa** [prashants/webzash#1]
Instead of running it in "example.com/**webzash**".

What are the steps to take to achieve above?

**Comment by superleo-cn** [comment]
It's not working. I followed the steps, still cannot work it out.
The URL is: 
http://account.weebo.com.sg/

**Comment by prashants** [comment]
https://www.youtube.com/watch?v=ikRwcAGw9o0

Please use the latest version from the website
