### ISSUE TITLE
Auto suggestion for Ledger, instead of finding in a big list.

### ISSUE THREAD

**Issue by ganesh14** [prashants/webzash#10]
Could you add the auto suggestion feature in the ledger selection instead of a tedious process of selecting from the list. we can have the drop down with auto suggestion, it will help to find the required ledger easily even if you have forgotten.

**Comment by prashants** [comment]
https://github.com/prashants/webzash/issues/9

**Comment by prashants** [comment]
Added in the latest commit.

How to update plugin

https://github.com/prashants/webzash/wiki/Webzash-update-plugin

Please follow the https://github.com/prashants/webzash/issues/9 issue
