### ISSUE TITLE
Forgot username and password

### ISSUE THREAD

**Issue by fuzzycashews** [prashants/webzash#101]
Hi,

This is shiva from chennai. I was used this software for 6 months but now i forgot my username and password... I have tried more than once and it showing some errors like minimum 5 attempts only you can take. You need to ask permission to administrator to re-active this account. Is there any possible way to re-activate the account? Can someone help me as soon as possible.

**Comment by codeezer** [comment]
You can manually change the password from sqlite db. It might not the recommended way but it should work. :)

**Comment by prashants** [comment]
https://github.com/prashants/webzash/wiki/General-FAQ#q3-what-to-do-if-i-forget-my-administrator-password
