### ISSUE TITLE
Internationalizing Webzash?

### ISSUE THREAD

**Issue by marteserede** [prashants/webzash#11]
Wouldn't it be great, to be able to change the language of the application?
I think CakePHP offers a not too difficult way to do that. First of all, all strings have to be wrapped in __()
And then in the next step, people could write translation-files.
What else needs to be done?
The question is, if you also want to internationalize the database-entries, but I don't know if in the first step that would be so important... I mean for example the ledger names and so on. Those can be translated manually.

**Comment by prashants** [comment]
string are already wrapped in __()

You need write the translations files

It is not possible to translate ledger names easily.

**Comment by marteserede** [comment]
Oh, already I already had a look into the code, I overlooked that all strings are already wrapped in __(). That is great.
I will start translating and also try to create the possibility to change the language.
Shall the be the possibility to change it when logging in or as an account setting? What do you think?

**Comment by prashants** [comment]
> Shall the be the possibility to change it when logging in or as an account setting? What do you think?

That can be done.

Let me know how it goes. I am using the __d('webzash', 'string...') function for printing strings.

**Comment by datamaskinen** [comment]
I can help you translating into swedish

**Comment by prashants** [comment]
That will be great. Let me know if you face any issues.

**Comment by deamonunix** [comment]
Sir prashants, i have wonder if it is possible to integrate the Barcode Scanner to the Inventory Module posted by mandaranga2? thank you.

**Comment by kapil247** [comment]
i will try to translate it italian, ofcourse would need someone who knows the accounting terms :o)
thanks a lot for the projec and hope that we can integrate it with barcode and other systems

**Comment by prashants** [comment]
Barcode can be integreated. Refer the extra fields patch

https://github.com/prashants/webzash/wiki/Extra-fields

**Comment by lognaume** [comment]
Hi guys, has someone already prepared the base translation file ? (e.g the "pot") ?
We may be interessed to start a french translation but having a base file would be appreciated instead of looking in each View to find strings ;)

**Comment by prashants** [comment]
Better ask questions related to translations on google groups since you are not getting any response here.

**Comment by datamaskinen** [comment]
hi,
Sorry for not replying...
I have not had The time yet to start looking at this yet and i will not be
alla to to do so in a While as well because of being newly employed by a
company and alot of ner things to learn and so on...

Regards
Martin
Den 27 nov 2015 07:01 skrev "Prashant Shah" <notifications@github.com>:

**Comment by prashants** [comment]
I have written a simple guide for translating the application in any language

https://github.com/prashants/webzash/wiki/Translations

It works with the v2.7-beta branch

https://github.com/prashants/webzash/tree/v2.7-beta

Hope this helps.

**Comment by felixivance** [comment]
I can help in translating into kiswahili (kenyan language)

**Comment by prashants** [comment]
That will be great.

**Comment by lognaume** [comment]
Nice, thank you for the translation guide. I'll begin the french translation once I'll have some free time.
