### ISSUE TITLE
easy improvement: ledger statement, add entry button

### ISSUE THREAD

**Issue by kylepwarren** [prashants/webzash#111]
maybe you could have 2 buttons, one fore credit or debit, doesn't really matter.
I guess one of the lines in the entry could be pre-populated with the related ledger statement's account.
You can already edit entries from this screen, would make sense to be able to add as well.

this is pretty easy / low hanging fruit.

**Comment by prashants** [comment]
Please send a patch and I will see if it can be included in next release.
