### ISSUE TITLE
where is this project going?

### ISSUE THREAD

**Issue by kylepwarren** [prashants/webzash#112]
It seems pretty useful. Just some questions:

1. It looks like you moved to cakephp in 2014. Do you think it will move to anything else in the future? Never been a big fan of php frameworks, php is already one of the highest level languages. What I see most of the frameworks doing is re-writing worse versions of things that php already does, e.g. they often have their own JSON libraries that are full of encoding problems. Also it's an upgrade dependency. When is it ok to upgrade cake? Shouldn't this whole thing either be a composer repo, and/or a git repo(I mean an entirely functional web application, not just a plugin)? a framework, ok. but having to upgrade separately, that's a lot of maintenance. I've never released a composer package[I prefer the everything in github idea, git clone and pull are pretty simple], not trying to say it was an obvious thing to do, just want a good upgrade path / avoid tons of weird maintenance stuff.

**Comment by prashants** [comment]
Will make the necessary changes in the next version.

I will stick with cakephp 2.x since changing that will be a total rewrite and it works decently and I have updated cakephp to latest version of 2.x few months back.

**Comment by MarcHe124** [comment]
The UI looks out of date. We can refresh the UI and welcome bootstrap4. Maybe I can contribute to that part. I also purchased bootstrap4 MD. The UI looks awesome.

**Comment by kylepwarren** [comment]
The ui is fine. You should accept my pull request. I tested it pretty well. Do you have some CI tests? I don't know how to run those. My branch is like 7 commits ahead

**Comment by prashants** [comment]
Thanks. Will look into it next week.
