### ISSUE TITLE
Oh Snap ! Something went wrong while adding database triggers. Please try again.

### ISSUE THREAD

**Issue by petersj77** [prashants/webzash#12]
I keep getting the error message "Oh Snap ! Something went wrong while adding database triggers. Please try again." when trying to set up an account in Webzash 2.3 (also had tried 2.2 last week as well)

I am installing on shared hosting with MySQL 5.5.38. The database admin account has ALL permissions

Any ideas as to what the issue could be?

**Comment by prashants** [comment]
Can you try creating the triggers manually from app/Plugin/Webzash/Config/Triggers.Mysql.sql

Before doing that search for '%_PREFIX_%' and replace with empty string in the same file.

I just created a account locally and it works on my end.

**Comment by prashants** [comment]
Maybe even drop the database and create a fresh one and then try again.

**Comment by petersj77** [comment]
Thanks

When I try to manually import the Triggers.mysql.sql file into the database via MySQLAdmin, I get the error message "#1419 - You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable) "

So I guess I don't have the SUPER privilege for creating triggers on our shared hosting package

**Comment by prashants** [comment]
Maybe if you want you can just skip the triggers since they are there for data verification and nothing more. Comment out line no 284 to 298 in the file app/Plugin/Webzash/Controller/WzaccountsController.php

**Comment by petersj77** [comment]
Thanks, that sorted it

**Comment by prashants** [comment]
Also comment out line 334 to 348 in app/Plugin/Webzash/Controller/SettingsController.php

**Comment by ngaboyera** [comment]
Dear Sir, 

My Webzash is installed on the following address: www.myfagerorg/demos/ahadi 
I had the same problem but when I try to  comment out the above mentioned lines I get the following message:

Errors
Fatal Error
Error: syntax error, unexpected ';', expecting ')'	
File: /hermes/bosoraweb033/b1713/ipg.myfagerorg/demos/ahadi/app/Plugin/Webzash/Controller/WzaccountsController.php	
Line: 349

Notice: If you want to customize this error message, create app/View/Errors/fatal_error.ctp

Any more help will be appreciated.

Thank you

Valens

**Comment by ngaboyera** [comment]
Sorry I mean www.myfager.org/demos/ahadi

**Comment by prashants** [comment]
Please check whether you are commenting the correct files and the correct lines.

Comment out line 284 to 298 in app/Plugin/Webzash/Controller/WzaccountsController.php
Comment out line 334 to 348 in app/Plugin/Webzash/Controller/SettingsController.php

Post the file on github gist https://gist.github.com/ if you still face issues

**Comment by ngaboyera** [comment]
Dear Prashants,

Thank you so much!

Now I can see that I was only commenting out lines in one file instead of two. I see that now that it works after considering your guidance. And I would like to know if the triggers can then be reactivated after the account is set.

**Comment by prashants** [comment]
You can add the triggers anytime. BTW I will removing triggers in future versions since too many people are facing this issue.

**Comment by prashants** [comment]
Triggers are removed in the beta version. All validations are done in code itself now.
