### ISSUE TITLE
Missing Database Connection

### ISSUE THREAD

**Issue by lantha** [prashants/webzash#121]
Missing Database Connection

Error: A Database connection using "Sqlite" was missing or unable to connect.
The database server returned this error: Selected driver is not enabled

Error: Sqlite driver is NOT enabled

Notice: If you want to customize this error message, create app\View\Errors\missing_connection.ctp

**Comment by lantha** [comment]
![1](https://user-images.githubusercontent.com/5203659/40315565-70c6cefe-5d3b-11e8-90fa-536a1a130359.PNG)
![2](https://user-images.githubusercontent.com/5203659/40315571-734774da-5d3b-11e8-952a-cfafc0181bf1.PNG)

**Comment by lantha** [comment]
I got into this problem in a fresh installation of Webzash. I have tried bitnami and other wamp variants but the problem remains. Also, tried downloading different copies of the tar and zip files of webzash, but its not working.

**Comment by lantha** [comment]
another problem in a fresh install
![1](https://user-images.githubusercontent.com/5203659/40340503-ee9128ee-5d9e-11e8-93a9-0f0105d47d0f.PNG)

**Comment by prashants** [comment]
Did you solve the sqlite problem ?

**Comment by lantha** [comment]
I think using php7 and not php5.x got over the sqlite issue but i cannot be certain on that but the class not found error persists.

**Comment by prashants** [comment]
I am closing this issue since there is not reply from the user.

**Comment by mytbi** [comment]
I am having the same problem but with webzash 2.9 and php 7.4.14
Errors
Missing Database Connection
Error: A Database connection using "Sqlite" was missing or unable to connect.
The database server returned this error: Selected driver is not enabled

Error: Sqlite driver is NOT enabled

Notice: If you want to customize this error message, create app\View\Errors\missing_connection.ctp

Stack Trace
CORE\Cake\Model\ConnectionManager.php line 105 → DboSource->__construct(array)
CORE\Cake\Model\Model.php line 3659 → ConnectionManager::getDataSource(string)
CORE\Cake\Model\Model.php line 1162 → Model->setDataSource(string)
CORE\Cake\Model\Model.php line 3686 → Model->setSource(string)
CORE\Cake\Model\Model.php line 834 → Model->getDataSource()
APP\Plugin\Webzash\Controller\WzusersController.php line 386 → Model->__call(string, array)
[internal function] → WzusersController->login()
CORE\Cake\Controller\Controller.php line 499 → ReflectionMethod->invokeArgs(WzusersController, array)
CORE\Cake\Routing\Dispatcher.php line 193 → Controller->invokeAction(CakeRequest)
CORE\Cake\Routing\Dispatcher.php line 167 → Dispatcher->_invoke(WzusersController, CakeRequest)
APP\webroot\index.php line 117 → Dispatcher->dispatch(CakeRequest, CakeResponse)
