### ISSUE TITLE
Order accounts with legder code

### ISSUE THREAD

**Issue by lakuapik** [prashants/webzash#124]
Hi, 

I recently use Webzash, and i dont see a menu/button to sort accounts by its ledger code.

How can we order accounts by ledger code? 

Thanks in advance.

**Comment by s-mcdonald** [comment]
Hi Lakuapik. I have recently started using this software also and have the same issue.

When I look at SQL database there doesnt seem to be a way of sorting these values. I assumed that it should sort on the Account/Ledger Code but it doesnt. I will see if I can make a fix for this and post the solution to **prashants**

**Comment by prashants** [comment]
https://github.com/prashants/webzash/blob/master/Lib/AccountList.php#L192

Change the order by clause to order by 'Ledge.code' instead of 'Ledger.name'
