### ISSUE TITLE
Cannot access it under domain.

### ISSUE THREAD

**Issue by superleo-cn** [prashants/webzash#13]
I follow the WIKI, https://github.com/prashants/webzash/wiki
but it's not working properly.
My testing URL is :
http://account.weebo.com.sg/

**Comment by prashants** [comment]
https://www.youtube.com/watch?v=ikRwcAGw9o0

Please use the latest version from the website. You dont have to make any changes from your side. Latest version should run without any modifications.

Dup of #1

**Comment by superleo-cn** [comment]
OK, I will try it soon and let you know.

**Comment by superleo-cn** [comment]
Still cannot work it out.

**Comment by prashants** [comment]
Which setup did you download ? I suggest you delete everything and retry. I think there is some issue with the upload.

**Comment by superleo-cn** [comment]
version 2.3. I found the below error:

[Wed Jan 28 17:25:15.916111 2015] [:error] [pid 18026] [client 115.42.245.38:20508] PHP Fatal error:  Class 'PDO' not found in /var/www/html/webzash/lib/Cake/Model/Datasource/Database/Sqlite.php on line 132
[Wed Jan 28 17:25:19.220065 2015] [:error] [pid 18027] [client 115.42.245.38:8977] PHP Fatal error:  Class 'PDO' not found in /var/www/html/webzash/lib/Cake/Model/Datasource/Database/Sqlite.php on line 132

**Comment by superleo-cn** [comment]
But I only use MySQL database.

**Comment by prashants** [comment]
Webzash uses Sqlite3 to store user info.

You can switch to MySQL if sqlite3 is not supported

https://github.com/prashants/webzash/wiki/MySQL-for-user-and-account-information

**Comment by superleo-cn** [comment]
I following your steps, still cannot work.

Same error:

Not Found

The requested URL /wzusers/login was not found on this server.

http://account.weebo.com.sg/wzusers/login

**Comment by prashants** [comment]
Can you give ftp access. I need to check it.

**Comment by superleo-cn** [comment]
Do you know how to use pem to connect to SFTP? I can mail your the pem file.

**Comment by prashants** [comment]
I can try. My email is available at http://webzash.org/contact

**Comment by superleo-cn** [comment]
Sent already.

**Comment by prashants** [comment]
Got it

**Comment by prashants** [comment]
I think you forgot to move hidden files : .htaccess is missing

**Comment by prashants** [comment]
I dont have permissions to move files around. You will have to do this.

**Comment by superleo-cn** [comment]
You mean i need to delete the .htaccess file?

**Comment by superleo-cn** [comment]
I moved the .htaccess file to the root folder already.

**Comment by prashants** [comment]
I suggest you delete the entire webzash folder and extract it again.

**Comment by prashants** [comment]
Also restart the apache server after that.

Which guide did you follow to setup the server ?

**Comment by prashants** [comment]
Dont move anything after extracting. Just extract and check in browser if it works without changing anything.

**Comment by prashants** [comment]
Can you give me write permissions to the folder ?

**Comment by superleo-cn** [comment]
i didn't change anything, just directly unzipped the file.

the archive file is : /var/www/html/webzash-v2.3.zip

zip path is: /var/www/html/webzash

you may use pem to login and change to root

Login:
ssh -i GuangHui-WebServer.pem
ec2-user@ec2-54-254-145-129.ap-southeast-1.compute.amazonaws.com
after login run:

sudo su -

**Comment by prashants** [comment]
Cool. Working on it.

http://account.weebo.com.sg/cakephp/ -> URL rewrite issue

**Comment by prashants** [comment]
http://account.weebo.com.sg/webzash/wzusers/login

**Comment by prashants** [comment]
Here is what you have to do :

1. Edit the httpd.conf and set AllowOverride to all from none
http://stackoverflow.com/questions/12292992/permalinks-on-wordpress-ec2

2. Restart apache server.

I had extracted a fresh copy of webzash in the /var/www/html/webzash/webzash folder and it works.

I have undone all the changes that I have made to httpd.conf and a original copy is available at /etc/httpd/conf/httpd.conf.webzash-original

You have set AllowOverride as per your security settings.

**Comment by prashants** [comment]
I have reverted all changes that I have made to httpd.conf and restarted the apache server.

**Comment by superleo-cn** [comment]
I still cannot access it from http://account.weebo.com.sg/

**Comment by prashants** [comment]
http://account.weebo.com.sg/webzash/

**Comment by prashants** [comment]
Now check http://account.weebo.com.sg/

**Comment by superleo-cn** [comment]
Oh, great!!!  Thank you very much.  May I know what you changed ?

**Comment by prashants** [comment]
Edit the httpd.conf and set AllowOverride to All from none

http://stackoverflow.com/questions/12292992/permalinks-on-wordpress-ec2

**Comment by superleo-cn** [comment]
Fixed. Thanks very much.

**Comment by superleo-cn** [comment]
Oh, I see. Sorry, I am not familiar with PHP.  I will start to install it,
thanks a lot.
