### ISSUE TITLE
Petty Cash Ledger Opening balance incorrect on page 2 of ledger

### ISSUE THREAD

**Issue by WWS1** [prashants/webzash#130]
I have found that the 2nd page of the Petty cash ledger opening balance actually shows the page 2 closing balance! The page 2 closing balance shows the actual page 2 closing balance + the page 2 total again.
ie if page 1 closing balance is 200 and the total of page 2 is 300 then the opening balance on page 2 shows 500 and the closing balance on page 2 shows 800.

Thanks

**Comment by prashants** [comment]
Are you using the latest version of webzash ? There was some problem with earlier versions. Also, please post a screenshot.

**Comment by WWS1** [comment]
Thank you for such a speedy response. I have installed two instances of the same version for two different businesses which i believe to be the latest version, on different servers, one is operating without issue for the one business and the other is as described which is confusing. Both databases were updated from an old version we used. Could this be a corrupt database problem or php version problem?? Everything else seems to be working correctly? I will send screen shots on Monday as I am not at my desk at the moment. 
Thank you
Regards 
Graham
On 30 Jun 2018 2:14 pm, Prashant Shah <notifications@github.com> wrote:Are you using the latest version of webzash ? There was some problem with earlier versions. Also, please post a screenshot.

**Comment by WWS1** [comment]
Hi Prashant,

 

Attached are screen shots of the issue.

 

Thanks

 

 

 

 

Best regards

Graham Savine-Jones

 

Tel: 01952 246557

www.wwswebservices.co.uk <http://www.wwswebservices.co.uk.co.uk/> 

 

 

This message and any attachments are confidential and should only be read by those to whom they are addressed. If you are not the intended recipient, please contact us, delete the message from your computer and destroy any copies. Any distribution or copying without our prior permission is prohibited.

Internet communications are not always secure and therefore we do not accept legal responsibility for this message. The recipient is responsible for verifying its authenticity before acting on the contents. Any views or opinions presented are solely those of the author and do not necessarily represent those of our company.

P Please consider the environment before printing this e-mail

**Comment by WWS1** [comment]
Hi Prashant I have also two more issues.

 

Firstly The account year dates are from 1st of Feb to 31st Jan each year and no entries can be made for the 31st Jan at the end of the year as it starts at 31st Jan instead of the 1st feb.

 

And secondly It will only print partial ledger statements and not the full ledger?

This is on the installation that I thought was ok?

 

 

Thanks

 

Best regards

Graham Savine-Jones

 

Tel: 01952 246557

www.wwswebservices.co.uk <http://www.wwswebservices.co.uk.co.uk/> 

 

 

This message and any attachments are confidential and should only be read by those to whom they are addressed. If you are not the intended recipient, please contact us, delete the message from your computer and destroy any copies. Any distribution or copying without our prior permission is prohibited.

Internet communications are not always secure and therefore we do not accept legal responsibility for this message. The recipient is responsible for verifying its authenticity before acting on the contents. Any views or opinions presented are solely those of the author and do not necessarily represent those of our company.

P Please consider the environment before printing this e-mail

**Comment by prashants** [comment]
The messages are totally messed up and I cant see any screenshots.

Are you still facing problems ?

**Comment by cjsingh** [comment]
I am facing the same problem:
![image](https://user-images.githubusercontent.com/43475835/45888816-a005f580-bddc-11e8-9a8a-8991c1ecad10.png)
![image](https://user-images.githubusercontent.com/43475835/45888839-aeeca800-bddc-11e8-94af-4fa901b2f4f6.png)

Also the ledger prints first two pages only - in csv, xls as well as normal print.

**Comment by WWS1** [comment]
I gave up on this project too many issues and incorrect information etc.. now using http://www.Waveapps.com totally free and really excellent to use as good as quickbooks any day.

**Comment by prashants** [comment]
@cjsingh 

Can you come on teamviewer.

**Comment by prashants** [comment]
https://github.com/prashants/webzash/issues/86

There was a bug with MySQL with older version of webzash long ago for which I had patched it. Are you sure that you are using the latest version ? I have not seen this error with the latest version.

**Comment by cjsingh** [comment]
This is solved. There wasn't any issue with the software. Apparently some cache issue in my browser. Restarted and it is showing correct balances. Thanks to Prashant for a quick response and help. Really appreciate.

**Comment by prashants** [comment]
Change the maximum number of row count in Administrator > Settings to less than 100. Logout and login again.

**Comment by prashants** [comment]
Let me know if it fixes the problem.
