### ISSUE TITLE
Import or Restore Accounts

### ISSUE THREAD

**Issue by ventolinmono** [prashants/webzash#131]
Hi

Downloaded sql.gz Webzash databases from an online installation and i want to import them to a local installation. phpMyAdmin import gets the following error:

SQL query:
-- Table structure for table `entries`
DROP TABLE IF EXISTS `entries`
MySQL said: Documentation
#1046 - No database selected.

**Comment by prashants** [comment]
As the error says "No database selected". You have not selected the database.

**Comment by prashants** [comment]
I am closing this issue since there is not reply from the user.
