### ISSUE TITLE
Download Ledger Statement in xls./csv.

### ISSUE THREAD

**Issue by faraz07** [prashants/webzash#134]
Hi Prashant, 
Hope you doing good, it is really a nice software and very user friendly as well. All the required features are already available, so useful. Am having an issue in downloading ledger statement in xls / csv. Whenever i click on the download button to down statement in xls., it always downloads limited data. Its not downloading complete ledger statement. Same is happening in downloading csv. format and with Print as well. Can you please help out in same.
Your solution will be awaited.

Many Thanks.

**Comment by faraz07** [comment]
Hi, Can any one help me out in resolving this issue.

**Comment by prashants** [comment]
It is fixed in v2.8 beta

You can simply replace this file if you dont want to do a full update since v2.8 is expected soon.

https://github.com/prashants/webzash/blob/v2.8-beta/Controller/ReportsController.php

Let me know if it fixes the issue.

**Comment by faraz07** [comment]
Many many thanks Prashant. The issue is resolved. 
Thanks for your great help.

**Comment by prashants** [comment]
The latest version 2.8 should fix this issue. If not reopen this issue.
