### ISSUE TITLE
Total of Dr / Cr on each page of Ledger Statement

### ISSUE THREAD

**Issue by faraz07** [prashants/webzash#135]
Hi Prashant,
Hope you are doing good. Your software is very helpful and very user friendly. I used to work on it daily basis and found very useful.
I just found a miner thing that there is no Total of Debit & Credit on each page of Ledger Statement. 
Could you pls help me out in this, or send me the updated script/file, so that i can update the same in my project. Attaching screenshot for your reference.
![image](https://user-images.githubusercontent.com/46316787/55323751-630c7100-5499-11e9-8e53-245b791347e8.png)

Your reply will be awaited.
Thanks.

**Comment by faraz07** [comment]
Hi Prashant,
your help in same will be highly appreciated.
Waiting for your earliest response.

Thanks.

**Comment by prashants** [comment]
Which version are you using ?

**Comment by faraz07** [comment]
Application version : 2.5
Application database version : 6
PHP version : 5.6.19
PHP BC Math library : Yes

**Comment by prashants** [comment]
Please update to latest version

https://github.com/prashants/webzash/wiki/Webzash-upgrade-v2.x

**Comment by faraz07** [comment]
Thanks for your quick reply Prashant, can you pls give me any patch code, thru which i can update the same in my current project?

**Comment by faraz07** [comment]
Hi Prashant, i have done some customization in current project. If i upgrade the project to latest version, so will all the customization i have done would be losted? Can you pls guide, how can i prevent my customization,

**Comment by faraz07** [comment]
Hi Prashant, can you pls guide on same.

Mnany Thanks.

**Comment by prashants** [comment]
You can use diff to save your changes and then port them back to the new
version.

Keep a backup ready just in case.

**Comment by arabhi** [comment]
Hi Prashant,
There is not available the DR, CR total in statement too.

**Comment by prashants** [comment]
Fixed in beta v2.9 branch https://github.com/prashants/webzash/tree/v2.9-beta

If you dont want to do a full update just replace this file

View/Reports/ledgerstatement.ctp
