### ISSUE TITLE
Cound not connect to database. Please, check your database settings.

### ISSUE THREAD

**Issue by superleo-cn** [prashants/webzash#14]
Please take a loot at the screenshot.

![01](https://cloud.githubusercontent.com/assets/4060241/5958168/dc62546e-a7fc-11e4-8375-316be0a4144f.png)

**Comment by prashants** [comment]
Did you create the database first ?

**Comment by superleo-cn** [comment]
Yes, I create a database named webzash and use MasterSchema.MySQL.sql to init it.

**Comment by prashants** [comment]
Please check the installation video on the webzash.org help section.

**Comment by superleo-cn** [comment]
Fixed. Thanks.
