### ISSUE TITLE
Massive spam of "undefined variable"

### ISSUE THREAD

**Issue by mwkcoding** [prashants/webzash#143]
The site when following the installation guide looks like this:
![image](https://user-images.githubusercontent.com/16936030/74648203-81e12800-517d-11ea-9243-573811e14555.png)

Very user-friendly...

**Comment by shifat-hossain** [comment]
May be it's php version related. I got this problem in php 7.4 version but not get problem in php 7.3

**Comment by prashants** [comment]
> May be it's php version related. I got this problem in php 7.4 version but not get problem in php 7.3

Some issue with latest version of PHP. I am working on the fix.

**Comment by prashants** [comment]
Updating cakephp to latest 2.x fixes the issue.

I will be releasing v2.9 this week that will fix this issue.

**Comment by prashants** [comment]
Webzash v2.9 available for download.

Guide on how to update from previous 2.x versions :-

https://github.com/prashants/webzash/wiki/Webzash-upgrade-v2.x

This should fix this issue. Closing it. If it is still showing errors feel free to reopen this issue.
