### ISSUE TITLE
Missing Database Connection - webzash 2.9 and php 7/4/14

### ISSUE THREAD

**Issue by mytbi** [prashants/webzash#149]
I am having the same problem but with webzash 2.9 and PHP 7.4.14
Errors
Missing Database Connection
Error: A Database connection using "Sqlite" was missing or unable to connect.
The database server returned this error: Selected driver is not enabled

Error: Sqlite driver is NOT enabled

Notice: If you want to customize this error message, create app\View\Errors\missing_connection.ctp

Stack Trace
CORE\Cake\Model\ConnectionManager.php line 105 → DboSource->__construct(array)
CORE\Cake\Model\Model.php line 3659 → ConnectionManager::getDataSource(string)
CORE\Cake\Model\Model.php line 1162 → Model->setDataSource(string)
CORE\Cake\Model\Model.php line 3686 → Model->setSource(string)
CORE\Cake\Model\Model.php line 834 → Model->getDataSource()
APP\Plugin\Webzash\Controller\WzusersController.php line 386 → Model->__call(string, array)
[internal function] → WzusersController->login()
CORE\Cake\Controller\Controller.php line 499 → ReflectionMethod->invokeArgs(WzusersController, array)
CORE\Cake\Routing\Dispatcher.php line 193 → Controller->invokeAction(CakeRequest)
CORE\Cake\Routing\Dispatcher.php line 167 → Dispatcher->_invoke(WzusersController, CakeRequest)
APP\webroot\index.php line 117 → Dispatcher->dispatch(CakeRequest, CakeResponse)

**Comment by prashants** [comment]
You need to enable Sqlite 3 driver with PHP
