### ISSUE TITLE
Date Format v1 to v2 update

### ISSUE THREAD

**Issue by lofttroy** [prashants/webzash#15]
First, thank you for your efforts on producing this software.  On an update from v1 to v2 (db v4 to v5) the date format is not updated correctly.  v4 has a single date format and v5 has multiple formats separated by a '|'.  Manually changing the date format in the database corrects the issue so it should just a simple update query.

**Comment by prashants** [comment]
Thanks. Will fix it.

**Comment by prashants** [comment]
Fixed
