### ISSUE TITLE
Self-hosted on HostGator: Cant install - internal server error

### ISSUE THREAD

**Issue by tanzanian** [prashants/webzash#152]
Hi,

Uploaded zipped folder to shared hosting and extracted. 

Upon visiting /webzash we get the following error:

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at 9deleted) to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by jessicana** [comment]
Hello,
I tried to install it in the same way, and I encountered the same problem. This is most probably related to permissions. Could you please do the following:
1. Provide us with your system configuration.
2. If Linux, please follow: https://github.com/prashants/webzash/issues/150 
3. Please check your PHP error log and post the entries here (if not resolved after going through the above link).

**Comment by prashants** [comment]
If you are getting error try locally first using a stack installer. 

thanks @jessicana

**Comment by tanzanian** [comment]
Thank you @jessicana & @prashants 
The issue was to do with some code in .htaccess 
Upon sorting the same, the installation loaded
I am in the process of setting it up. Will create a new issue if I get stuck.
