### ISSUE TITLE
Recommendation for retroactive accounting

### ISSUE THREAD

**Issue by jessicana** [prashants/webzash#153]
Hello Sir! 
I want to enter the accounting transactions for company ABC LLC since its inception in 2014 up to the current year, 2021. This will require eight years of accounting that I will keep open in the system until the IRS audits the records and I get the tax returns certified. I will keep recording transactions for all years without closing any of them (i.e., I will keep them unlocked). What is the best practice I can follow to do that in Webzash? 

What I tried to do but it did not work is going to Administrator Dashboard > Create Account > and I used the same database details, but it showed errors (I left some examples below). Do you think I have to create eight databases, one for each year? Can't I maintain all of the accounting years on one database? 

```
Table with the same name as "entries" already existsin the "databasename" database. Please, use another database or use a different prefix.

Table with the same name as "entryitems" already existsin the "databasename" database. Please, use another database or use a different prefix.

Table with the same name as "entrytypes" already existsin the "databasename" database. Please, use another database or use a different prefix.

Table with the same name as "groups" already existsin the "databasename" database. Please, use another database or use a different prefix.

Table with the same name as "ledgers" already existsin the "databasename" database. Please, use another database or use a different prefix.

Table with the same name as "logs" already existsin the "databasename" database. Please, use another database or use a different prefix.

etc... 
```

**Comment by prashants** [comment]
Yes you need to create 8 database. I dont support multiple years accounts like the one you are trying to setup. If you have some restriction on database creation then you can try using database table prefix which will give different table prefix for each year within same database.

You already have account and you are creating another one over it hence the error.

**Comment by jessicana** [comment]
Thank you very much! The table prefix worked like a charm. For example, for 2014, I used _14, and the accounts were created promptly on my testing stack. Do you recommend multiple databases, or am I safe using database table prefixes in my case? I have no restrictions on creating databases, and I will go for your recommendation on best practices for webzash.  If multiple, I will make them.

**Comment by prashants** [comment]
It's table prefix not suffix :) You should use 2014_ and not _14.

I recommend separate databases. Easier to backup and restore. Once accounts
for a particular year are completed, you can take backup of the database
once and forget about it.
