### ISSUE TITLE
Modify Role

### ISSUE THREAD

**Issue by febyferdinan** [prashants/webzash#16]
Dear Prashants,

I want to ask a few question about Role in Webzash, Can I modify the role? and how to modify that role, what file that should be modified?

Regards,

**Comment by prashants** [comment]
You want to modify the permissions associated with a role ?

**Comment by febyferdinan** [comment]
Yes, for example, I want to add Role Shareholders, and I want to grant Shareholders Role to access the Reports menu Only, they can’t access Accounts & Entries menu.

**Comment by prashants** [comment]
1. Add a array item to Controller/Component/PermissionComponent.php

    $permissions['shareholder'] = array(
      'access reports',
    );

2. Changre Model/Wzuser.php

'rule2' => array(
'rule' => array('inList', array('admin', 'manager', 'accountant', 'dataentry', 'guest')),
'message' => 'Invalid value for role',
'required' => true,
'allowEmpty' => false,
),

3. View/Helper/GenericHelper.php

Change wzuser_role() and wzuser_role_options()

**Comment by febyferdinan** [comment]
I can’t found file PermissionComponet.php, Wzuser.php & GenericHelper.php.

I use webzash v2.3, as attached.

**Comment by prashants** [comment]
Its in app/Plugin/Webzash :)

**Comment by febyferdinan** [comment]
Ok I found it.

For this step, I need more explanation, what should I change in this file? :

View/Helper/GenericHelper.php change wzuser_role() and wzuser_role_options()

**Comment by prashants** [comment]
In wzuser_role() add
    case 'shareholder': return __d('webzash', 'Shareholder');

In wzuser_role_options() add
    'shareholder' => __d('webzash', 'Shareholder'),

**Comment by febyferdinan** [comment]
Ok, the problem was solved, thank you for your support.

Now I have another question, how to add 1000 separator in all nominal in this system?

**Comment by prashants** [comment]
https://github.com/prashants/webzash/pull/4/files

**Comment by febyferdinan** [comment]
that was 100 separator, how about 1000 separator?

**Comment by prashants** [comment]
You have to change the function as per your requirement.

**Comment by febyferdinan** [comment]
Dear Prashants,

I have a few question :

1. Where did you store all users information like username, password, etc.
2. How do I recover admin password when I forget which email address that I’ve been registered?

Regards,

**Comment by prashants** [comment]
User info is stored in sqlite3 file in the app/Plugin/Webzash/Database folder.

Manually changing the email address / password in the above sqlite file. You can use the firefox sqlite manager plugin.

**Comment by ivanovsky1** [comment]
@prashants How can I add custom user capabilities? I.e. I want each user to see their own investment only. If so how can that be possible?
Thank you much...for your hard work
