### ISSUE TITLE
Development 

### ISSUE THREAD

**Issue by eliasyanni** [prashants/webzash#17]
Good work, simple and clean. Will be using it in one of my projects. What features are you thinking of developing in the future? I can help contribute to your project as I go. Should be free in the next month or so to begin. Let me know what you need help with and I maybe able to throw you some ideas as well.

**Comment by prashants** [comment]
Thanks for your support. I am looking to implment the following
- Implment Backup
- Add Postgres / MS SQL support
- Keyboard shortcuts
- Currency format
- Currency decimal places
- Update script
- Three digit decimal

**Comment by prashants** [comment]
Are you planning on working on anything ? Converting the MySQL script to Postgres will be really helpful. We want to support Postgres in the next release.

https://github.com/prashants/webzash/blob/master/Config/Schema.Mysql.sql

**Comment by prashants** [comment]
Thanks !

**Comment by prashants** [comment]
Most of the features are implemented in v2.5. Closing this.
