### ISSUE TITLE
how to handle cheque

### ISSUE THREAD

**Issue by maduranga2u** [prashants/webzash#20]
Are there any option for cheque details enter and generate reports

**Comment by prashants** [comment]
not in the current version

**Comment by maduranga2u** [comment]
I can develop this part please advised me.

**Comment by prashants** [comment]
just add a field in entries for cheque number and date.

**Comment by prashants** [comment]
Implemented the cheque number and date and per field narration in add and edit entries.

Follow the below guide

https://github.com/prashants/webzash/wiki/Extra-fields

There is still work to be done but this is final. You can apply the patch against you main account database. Do keep a backup beforehand though.

**Comment by deamonunix** [comment]
Good day Sir, i have another concern, if it is possible to integrate the barcode scanner to the inventory module of webzash, thank you sir prashants.

**Comment by prashants** [comment]
We dont have support for barcode scanner. If you implement it do send a pull request.
