### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by felixivance** [prashants/webzash#22]
i just encountered this error while i was using webzash 

Warning (2): getmypid() has been disabled for security reasons [CORE/Cake/Utility/String.php, line 85]

when i click on warning these are the details that appear
 $pid = zend_thread_id();

        } else {

            $pid = getmypid();

$node = (int) 1053972295

getmypid - [internal], line ??
String::uuid() - CORE/Cake/Utility/String.php, line 85
Security::generateAuthKey() - CORE/Cake/Utility/Security.php, line 66
SecurityComponent::generateToken() - CORE/Cake/Controller/Component/SecurityComponent.php, line 536
SecurityComponent::startup() - CORE/Cake/Controller/Component/SecurityComponent.php, line 245
ObjectCollection::trigger() - CORE/Cake/Utility/ObjectCollection.php, line 128
call_user_func - [internal], line ??
CakeEventManager::dispatch() - CORE/Cake/Event/CakeEventManager.php, line 242
Controller::startupProcess() - CORE/Cake/Controller/Controller.php, line 675
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 187
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 165
[main] - APP/webroot/index.php, line 108

i would really appreciate some knowledge on how to tackle the above error

thanks

**Comment by prashants** [comment]
http://stackoverflow.com/questions/17259084/cakephp-security-issue

**Comment by felixivance** [comment]
Awsome.. Solved my problem.
I am a freelance developer php and android.. Webzash is an awsome tool 
Thanks
