### ISSUE TITLE
Maintain Global Category Order

### ISSUE THREAD

**Issue by chacha** [prashants/webzash#24]
In commit 5638df06a254be1a3e9389534764018130ac7e35 you sort the account lists alphabetically. While I agree with this is an improvement, the general categories should maintain the order:

* Assets
* Liabilities
* Income
* Expenses

This is traditionally how they are kept on a COA.

**Comment by prashants** [comment]
On which page are they not in order ? As far as I remember the primary groups are not used in any of the queries.

**Comment by chacha** [comment]
In the main account listing the current primary groups order is Assets, Expenses, Income, Liabilities.

**Comment by prashants** [comment]
Fixed in beta version. Use the updated 3 files to fix this issue in current version.

#	modified:   Lib/AccountList.php
#	modified:   Lib/GroupTree.php
#	modified:   Lib/LedgerTree.php

**Comment by prashants** [comment]
Solved in latest release. Please use that.
