### ISSUE TITLE
Schema.php -> 7 technical errors tossed by netbeans

### ISSUE THREAD

**Issue by williamconley** [prashants/webzash#25]
Lines 212 & 213, missing ")" before "comma" at the end of the line after "false"

		'fy_start' => array('type' => 'date', 'null' => false,
		'fy_end' => array('type' => 'date', 'null' => false,

		'fy_start' => array('type' => 'date', 'null' => false),
		'fy_end' => array('type' => 'date', 'null' => false),

Lines 247-257 (odd), missing commas after "false"

		'print_paper_height' => array('type' => 'decimal', 'null' => false
			'default' => '0.000', 'unsigned' => false, 'length' => '10,3'),
		'print_paper_width' => array('type' => 'decimal', 'null' => false
			'default' => '0.000', 'unsigned' => false, 'length' => '10,3'),
		'print_margin_top' => array('type' => 'decimal', 'null' => false
			'default' => '0.000', 'unsigned' => false, 'length' => '10,3'),
		'print_margin_bottom' => array('type' => 'decimal', 'null' => false
			'default' => '0.000', 'unsigned' => false, 'length' => '10,3'),
		'print_margin_left' => array('type' => 'decimal', 'null' => false
			'default' => '0.000', 'unsigned' => false, 'length' => '10,3'),
		'print_margin_right' => array('type' => 'decimal', 'null' => false

Should be

		'print_paper_height' => array('type' => 'decimal', 'null' => false,
			'default' => '0.000', 'unsigned' => false, 'length' => '10,3'),
		'print_paper_width' => array('type' => 'decimal', 'null' => false,
			'default' => '0.000', 'unsigned' => false, 'length' => '10,3'),
		'print_margin_top' => array('type' => 'decimal', 'null' => false,
			'default' => '0.000', 'unsigned' => false, 'length' => '10,3'),
		'print_margin_bottom' => array('type' => 'decimal', 'null' => false,
			'default' => '0.000', 'unsigned' => false, 'length' => '10,3'),
		'print_margin_left' => array('type' => 'decimal', 'null' => false,
			'default' => '0.000', 'unsigned' => false, 'length' => '10,3'),
		'print_margin_right' => array('type' => 'decimal', 'null' => false,

**Comment by prashants** [comment]
Thanks for catching that. Will fix it in next version. It wont affect the application so you can still use it. The Schema.php is for my own internal reference and is not used anywhere.

**Comment by williamconley** [comment]
Good to know. Thanks for the note!
