### ISSUE TITLE
Webzash on Joomla 3.x

### ISSUE THREAD

**Issue by mbsarino** [prashants/webzash#3]
Hi! I'd like to be able to integrate Webzash with my Joomla 3.x installation.  Can this feature be added?

**Comment by mbsarino** [comment]
Hi Prashant!

I am doing a clean install of Webzash 2.2 and have gotten the following error:


Am I missing anything?  I was able to install previous versions as you know.
![capture - webzash 2 2setup](https://cloud.githubusercontent.com/assets/7676572/5625036/ff2af45c-95a4-11e4-90d0-3df321906afd.JPG)

**Comment by prashants** [comment]
Please check the url, webzash doesnt have anything called setup controller.

**Comment by mbsarino** [comment]
I have the Webzash files and folders (app, lib. plugins, etc) in a folder called "acc" my www folder.  As such the directory structure is: /wamp/www/acc/

When I go to http://172.64.15.9/acc/setup, that is the error I get.

**Comment by prashants** [comment]
Why are you going to http://...ip.../acc/setup ? You just have to open http://...ip.../acc without the "setup"

**Comment by mbsarino** [comment]
Oops!  My bad.  I was thinking of another app.

I have now setup Webzash and added the Joomla auth package.  I logged in to
Joomla and went to my Webzash app but this is what I got.

I have also attached my joomla auth php file.

Did I configure it wrong?

**Comment by prashants** [comment]
What did you get ?

You will have to relogin to webzash since its not possible to share the session data.

**Comment by mbsarino** [comment]
please see the attached files for the errors I got

**Comment by prashants** [comment]
I cant find the attached file.

**Comment by mbsarino** [comment]
ill send it to your email

**Comment by prashants** [comment]
ok

**Comment by prashants** [comment]
define("JOOMLA_PATH", "http://localhost/"); -> this should be the machine path not the url

C:\...\joomla

**Comment by mbsarino** [comment]
Thanks. Let me try that out.

**Comment by mbsarino** [comment]
I have now been able to install v.2.2 with the Joomla plugin.  However,
even after logging on to Joomla and then going to my webzash directory, it
still shows me the webzash login page.  Did I miss anything?  My username
and login for Joomla and Webzash is the same.

**Comment by prashants** [comment]
Its not possible to share sessions with joomla, so you will have to login again using your joomla credentials.

> Also, which fille do I need to edit agian to remove/replace the "Webzash" in the menubar?
https://github.com/prashants/webzash/wiki -> Q3

**Comment by mbsarino** [comment]
so the process would be:

1. Login to Joomla
2. Login to Webzash
3. Login to Joomla

?

**Comment by prashants** [comment]
Both are totally separate app, it just that they share the same login details.

Login to Joomla
Login to Webzash
....
....
Logout of Webzash
Logout of Joomla

**Comment by prashants** [comment]
Login in and out of both is totally isolated. They dont affect each other.

**Comment by mbsarino** [comment]
oh ok.

I was under the impression that it was an SSO.  If it isn't then it would
be the same as loggin into both apps seaparately as I previously had.

**Comment by prashants** [comment]
Yes you login separately but it shares the same user table.

**Comment by prashants** [comment]
I have integrated the Joomla auth in the main tree so that you can stay updated with the latest version in future. I am deleting the joomla-auth branch.

https://github.com/prashants/webzash/wiki/Third-Part-Login

Here is how to update

https://github.com/prashants/webzash/wiki/Webzash-update-plugin

**Comment by prashants** [comment]
https://github.com/prashants/webzash/wiki/Third-Party-Login

**Comment by prashants** [comment]
> what we are wanting to do is to login joomla and consequently be logged in to webzash

That is what I tried first, but the way joomla saves session is very secure and doesnt work with what cakephp does. It is not possible to share sessions across both easily.
