### ISSUE TITLE
Not able to Install on Live Server - GoDaddy

### ISSUE THREAD

**Issue by gopuvkm** [prashants/webzash#30]
Dear Sir

Greetings of the day...

Thanking you so much for a wonderful product. 

I am facing an issue with regard to installing webzash on a live server hosted by godaddy. It works fine with us on localserver using MAMP. We have used Masterconfig too to update the databse changes, but still we are not able to connect it

Your assistance is highly appreciated

Thanks

Gopan

**Comment by prashants** [comment]
please attach a screenshot or error message

**Comment by gopuvkm** [comment]
Please find the below
![screen shot 2015-09-19 at 5 19 14 pm](https://cloud.githubusercontent.com/assets/10255139/9976350/9c760906-5ef2-11e5-80d6-8329c8922068.png)

**Comment by prashants** [comment]
Please check if url rewrite is working and you have uploaded the hidden .htaccess file from the main folder.

**Comment by gopuvkm** [comment]
Can you please brief on the same

**Comment by gopuvkm** [comment]
It is done. But CSS are not shown properly

![screen shot 2015-09-19 at 5 40 51 pm](https://cloud.githubusercontent.com/assets/10255139/9976446/a1c4e9c4-5ef5-11e5-9dd2-688ec374e400.png)

**Comment by prashants** [comment]
Not installed properly. Why are links in source have webzash folder name in it ?

http://sitename/webzash/img/favicon.ico

**Comment by prashants** [comment]
Please delete everything and reupload from scratch.

**Comment by gopuvkm** [comment]
Thanks for your support. It done. However, I am not able to edit the entry or account even though, I have admin rights

**Comment by prashants** [comment]
What error you are getting ?

**Comment by gopuvkm** [comment]
No error. The system is not responding

**Comment by prashants** [comment]
can you directly paste the edit link in the browser url and see what happens.
