### ISSUE TITLE
The button "Add Entry" does not dropdown menu

### ISSUE THREAD

**Issue by aluni** [prashants/webzash#31]
I installed version 2.6 in my computer, in localhost in the operating system ubuntu.
I inserted groups and ledgers, but the button "Add Entry" does not work.
Do you know it can be?

**Comment by prashants** [comment]
There is a drop down button next to add entry. Click on that.

**Comment by aluni** [comment]
Yes, I know, but it does not work. 
thank you very much for your answer as fast.
I attached pictures of my screen for help you.
![ledger](https://cloud.githubusercontent.com/assets/4931189/10217295/2f7b0c52-682f-11e5-952f-e36b880db712.png)
![webzash](https://cloud.githubusercontent.com/assets/4931189/10217296/2f823b3a-682f-11e5-94b3-f4d98e4365bb.png)

**Comment by prashants** [comment]
I tested everything again on local machine and it is working correctly. Can you trying running the setup again.

Also have you made any changes ?

**Comment by aluni** [comment]
I tried again, but it had the same error, and I found out this text in error js: "Missing master sqlite database file. Please check your setup".
I don't have sqlite, I only executed "apt-get install php5-sqlite" and restarted apache2.
Thanks

**Comment by aluni** [comment]
The complete text is :<div class="cake-debug-output">
<span><strong>/app/Plugin/Webzash/Config/bootstrap.php</strong> (line <strong>326</strong>)</span>
<pre class="cake-debug">
&#039;Missing master sqlite database file. Please check your setup.&#039;
</pre>
</div>

**Comment by aluni** [comment]
Now it works, my database is MySQL, and this time I filled databasename but database schema was empty. What do you think?
Thanks for all

**Comment by prashants** [comment]
did you create account first ?

**Comment by aluni** [comment]
All times I did the same steps. I think if I remember correctly. the only difference was fill or not fill the field of database schema.

Thank you

**Comment by prashants** [comment]
Database schema is valid only for postgres sql.

**Comment by prashants** [comment]
There is a small note below the field that clarifies what to fill.

Note : Database schema is required for Postgres database connection. Leave it blank for MySQL connections.

Closing the issue.

**Comment by lofttroy** [comment]
I get this error intermittently.  Usually a restart of Apache fixes it.  I think you'll find that the first dropdown menu in the source code works correctly ('Settings'), but all following ones do not ('Entries').

**Comment by prashants** [comment]
That should not happen since the drop down has nothing to do with apache, since it runs on user browser. Maybe issue with apache caching or page speed ?

https://wiki.bitnami.com/Components/Apache/PageSpeed#How_to_disable_PageSpeed.3f
