### ISSUE TITLE
Required Account Name as Report Heading

### ISSUE THREAD

**Issue by XSLogicStudios** [prashants/webzash#32]
Hi is there any way to display Account Name on the Report. as report heading ?

**Comment by prashants** [comment]
You will have to change the below files as per your requirements.

https://github.com/prashants/webzash/tree/master/View/Reports/print

Use the following function :

<?php echo Configure::read('Account.name'); ?>
<?php Configure::read('Account.address'); ?>
<?php Configure::read('Account.email'); ?>
