### ISSUE TITLE
Allways display group code, even if it's "0".

### ISSUE THREAD

**Issue by kaiserfr** [prashants/webzash#35]
In the "chart of accounts" dialog the group codes are displayed in angular brackets like [1] for the group code "1". But if the group code is "0" it will not be displayed. Please display all group code strings literally.
(In my country exists a standard account numbering scheme and it starts with account group "0")

**Comment by prashants** [comment]
Make the following changes :

https://github.com/prashants/webzash/commit/dac0169a6bc9898dcfc5ea3f1ed9e0f6700e68ed
