### ISSUE TITLE
Changing the database of existing installation

### ISSUE THREAD

**Issue by XSLogicStudios** [prashants/webzash#36]
Hi Prashant,

I have customized quite things in the build now i need to change the db to testdb. how can i do that ?
is there any way i can change the connection string ?

Thanks,
ZS

**Comment by prashants** [comment]
if you want to change user database

https://github.com/prashants/webzash/wiki/MySQL-for-user-and-account-information

**Comment by prashants** [comment]
closing it. kindly reopen if problem not solved.

**Comment by MarimelL** [comment]
I've change that but I cannot create account for database.
