### ISSUE TITLE
adding 'approve' by administrator in entry 

### ISSUE THREAD

**Issue by yendrifernando** [prashants/webzash#44]
How we can adding 'approve' feature on webzash? Administrator should 'approve' the entry by the accountant if the payment > $200?

**Comment by prashants** [comment]
no such feature is currently present in webzash

**Comment by yendrifernando** [comment]
i mean step by step to add a new feature..

On 11/30/15, Prashant Shah <notifications@github.com> wrote:
> no such feature is currently present in webzash
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/prashants/webzash/issues/44#issuecomment-160525302


-- 


*@yendrifernando
**yendrifernando.wordpress.com*

**Comment by chacha** [comment]
Just from a process standpoint, the accounting books shouldn't be where your control flow happens. Accounting should be a reflection of the approval processes happening elsewhere. 

For instance, you might require a supervisor signature for any checks written out for $200+. But, that shouldn't happen at the accounting books level. The books reflect other processes. Placing the controls on the accounting software is going to lead to problems.

**Comment by yendrifernando** [comment]
thank you


On 12/1/15, Tyler Carter <notifications@github.com> wrote:
> Just from a process standpoint, the accounting books shouldn't be where your
> control flow happens. Accounting should be a reflection of the approval
> processes happening elsewhere.
>
> For instance, you might require a supervisor signature for any checks
> written out for $200+. But, that shouldn't happen at the accounting books
> level. The books reflect other processes. Placing the controls on the
> accounting software is going to lead to problems.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/prashants/webzash/issues/44#issuecomment-160729086


-- 


*@yendrifernando
**yendrifernando.wordpress.com*
