### ISSUE TITLE
offset error 

### ISSUE THREAD

**Issue by hidayat-ullah** [prashants/webzash#5]
I have Migrated to new one  but there is an error on the top bar 
which says 
Notice (8): Undefined offset: 1 [APP\Plugin\Webzash\Controller\WebzashAppController.php, line 140]

snap(http://i.imgur.com/nqtokHg.jpg)

And Due-to this error  date option is not working on any page

**Comment by prashants** [comment]
Let me know if you face any issue with adding the fields. I am closing this issue for now. Please open a new issues for extra fields.
