### ISSUE TITLE
Cannot add any more account groups

### ISSUE THREAD

**Issue by gmusgrave** [prashants/webzash#53]
I Logout, and then Login again.

I'm taken to the Administrator Dashboard page. I click on "Accounts".

I'm taken to my account's Account Dashboard. It says, "Account "LO20152016" activated." I click on "Accounts"

My Chart of Accounts is displayed. I click on "Add Group"

I'm taken to "Select account to activate" page with a message "All accounts deactivated". I select account "LO20152016" and click on "Activate"

I'm returned to my account's Account Dashboard. It says, "Account "LO20152016" activated." I click on "Accounts"

My Chart of Accounts is displayed. I click on "Add Group"

I'm again taken to "Select account to activate" page with a message Currently active account: "LO20152016", Select account. "LO20152016" is already selected in the drop-down box. I click on "Activate".

I'm returned to my account's Account Dashboard. It says, "Account "LO20152016" activated." I click on "Accounts"

My Chart of Accounts is displayed. I click on "Add Group"

I'm again taken to "Select account to activate" page with a message Currently active account: "LO20152016", Select account. "LO20152016" is already selected in the drop-down box. 

I'm stuck in this repeating cycle, unable to add an account group. Any help would be greatly appreciated.

**Comment by chacha** [comment]
Does anything else work, or is it limited to adding groups?

**Comment by gmusgrave** [comment]
At the time, I recall that I also could view a Balance Sheet report, but not a P&L report.

The weird thing is that I just logged in again to see exactly what else didn't work, so I could reply, and it all seems to be working now! Before I made my first post I logged in and out a few times, and got the behaviour I described.

The only big difference is the length of time I was logged out. I don't know if this is relevant or not. I've no idea what happened, or how to explain this. 

I'll monitor the situation, and report back if there are more problems. If so, I'll try to notice any patterns or circumstances.

**Comment by gmusgrave** [comment]
I successfully entered my remaining groups and accounts, and logged out.

**Comment by chacha** [comment]
Awesome. If everything is taken care of, please close this issue.

Thanks!

**Comment by prashants** [comment]
If in future if you face the same issue, email me the link to the server where you have hosted it.

**Comment by chacha** [comment]
@gmusgrave That's something that happens from time to time. We're working on making it less scary and less frequently. Security feature.

**Comment by prashants** [comment]
@chacha It should not happen. If you get black hole error then its because of the security feature to prevent Cross-Site Request Forgery. It comes inbuilt with CakePHP, I cant do much except for changing the error message or disabling it completely.

What @gmusgrave is facing is not because of that.

**Comment by gmusgrave** [comment]
After reading these replies, I went back to the website, and no login was required. I was taken straight to my account, and everything appears to work.

Very odd. Forgive me, but I'm not quite sure how I could have triggered a security feature just logging in and out from a single computer with a single browser.

If any of this happens again, I'll email @prashants with the link, as requested.
