### ISSUE TITLE
How to use MySql with webzash

### ISSUE THREAD

**Issue by GaneshKandu** [prashants/webzash#57]
Hi I am trying to install webzash with MySql but it using Sqllite whereas i Want in MySql
I Have changed "app/Config/database.php" as follow
```php
class DATABASE_CONFIG {

	public $default = array(
		'datasource' => 'Database/Mysql',
		'persistent' => false,
		'host' => <myhost>',
		'login' => '<login>',
		'password' => '<password>',
		'database' => '<database_1>',
		'prefix' => 'db1_',
		//'encoding' => 'utf8',
	);

	public $test = array(
		'datasource' => 'Database/Mysql',
		'persistent' => false,
		'host' => '<myhost>',
		'login' => '<login>',
		'password' => '<password>',
		'database' => '<database_2>',
		'prefix' => 'db2_',
		//'encoding' => 'utf8',
	);
}
```
I am using 
```php
'datasource' => 'Database/Mysql',
```
then also it using sqllite

**Comment by prashants** [comment]
https://github.com/prashants/webzash/wiki/MySQL-for-user-and-account-information

**Comment by GaneshKandu** [comment]
Ok !  Thax its working but getting trouble when  i am using prefix 

- CORE/Cake/Model/Model.php line 3566 → Model->setSource(string)
- CORE/Cake/Model/Model.php line 808 → Model->getDataSource()
- APP/Plugin/Webzash/Controller/WzsettingsController.php line 61 → Model->__call(string, array)
- APP/Plugin/Webzash/Controller/WzsettingsController.php line 61 → Wzsetting->findById(integer)
- [internal function] → WzsettingsController->edit()
- CORE/Cake/Controller/Controller.php line 490 → ReflectionMethod->invokeArgs(WzsettingsController, array)
- CORE/Cake/Routing/Dispatcher.php line 191 → Controller->invokeAction(CakeRequest)
- CORE/Cake/Routing/Dispatcher.php line 165 → Dispatcher->_invoke(WzsettingsController, CakeRequest)
- APP/webroot/index.php line 108 → Dispatcher->dispatch(CakeRequest, CakeResponse)

**Comment by prashants** [comment]
undo the changes made to app/Config/database.php

**Comment by GaneshKandu** [comment]
Ok ! Thax sir its working actually tables in MasterSchema.MySQL.sql  doesn't have a prefix and i am using prefix in MasterConfig.php may be that's why i am getting error
