### ISSUE TITLE
XSS Vulnerabilities.

### ISSUE THREAD

**Issue by Diantro01** [prashants/webzash#58]
Hello, 

As part of an academic project we found some XSS vulnerabilities in your code. 
We managed to produce a fixed version of the project. How would you like us to send it to you so that you can evaluate it?

Regards

**Comment by prashants** [comment]
Yes

**Comment by Diantro01** [comment]
Yes what? We already sent you an email as well

**Comment by prashants** [comment]
Got the email. Will look into it.

**Comment by prashants** [comment]
The way it was handled is to not filter user input but to filter when the data is displayed by passing it through the h() function. Can you help me with more details of what did you put in name field to trigger the vulnerability.

**Comment by Diantro01** [comment]
The first way is through the message you get everytime you add, edit or delete an item, the green bar that says "the  item has been added/deleted". There the test is not handled correctly and the vulnerability can be triggered.  The other method is in the "add entry" page tittle. If you edit an entry name to contain a javascript code in it, everytime a user tries to add a new entry of that type the script will be executed.  And since the add entry page can be accessed with a simple get without any post parameters, you could send an URL to your edited entry type add page and attack any logged in user. 

Hope that was clear, if not I can explain again

**Comment by prashants** [comment]
Can you try one change and see if it solves the issue.

In the app/Plugins/Webzash/View/Layouts/default.ctp

Change line number 73 where it displays the flash message to pass through the h()

    <?php echo h($this->Session->flash()); ?>

**Comment by Diantro01** [comment]
This still leaves the more persistent vulnerability open, the one that triggers in the tittle of the add entry page. 
(if an entry type is renamed to contain a script)

**Comment by prashants** [comment]
In the same file change the line no 68 to pass through h()

<?php echo h($title_for_layout); ?>

Let me know if it solves the problem.

**Comment by Diantro01** [comment]
The fix of the line 73 doesn't work as it breaks all the alert box. 

The one of the line 68 did work. 

To fix the alert box problem using h() we found you could do it in the  webzash/view/elements/success and danger.ctp both on line 29.

**Comment by prashants** [comment]
Great ! I hope this solves it. Will fix it in the next version.

**Comment by prashants** [comment]
I have fixed the reported vulnerabilities in the current branch, If you find more such vulnerabilities let me know.
