### ISSUE TITLE
Add 1000 separator (,) in Webzash

### ISSUE THREAD

**Issue by febyferdinan** [prashants/webzash#61]
Dear Prashants,

My question is how to add 1000 separator (,) in Webzash?

Thanks.
![webzash](https://cloud.githubusercontent.com/assets/11747941/14396908/8b870e40-fe04-11e5-839d-a51121548b77.png)

**Comment by chacha** [comment]
I believe you can set it in the options when you create each account.

**Comment by prashants** [comment]
Thanks chacha

You can also change it from Settings
