### ISSUE TITLE
webzash/wzusers/login Not Found in Ms Window Server

### ISSUE THREAD

**Issue by justin222** [prashants/webzash#62]
First of all thank you for the great work!

i have downloaded and installed webzash on my MS Window Server without using Bitnami. When I run "webzash/index.php" the browser was directed to  webzash/wzusers/login and it shown "Not Found". 
I checked there is no "wzusers" folder within the "webzash folder". I guess probably there is a "url-rewrite" or "redirection" involved. 

I understand that it's the best to use apache server but the server i am using is running under MS. Can you advise me how to get it work and if there is any "url-rewrite" involved which file should i direct my browser to?

Thank You.

**Comment by justin222** [comment]
solved :)

**Comment by prashants** [comment]
How ?

**Comment by justin222** [comment]
create a webconfig file with following content:
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="Exclude direct access to webroot/*"
                  stopProcessing="true">
                    <match url="^webroot/(.*)$" ignoreCase="false" />
                    <action type="None" />
                </rule>
                <rule name="Rewrite routed access to assets(img, css, files, js, favicon)"
                  stopProcessing="true">
                    <match url="^(img|css|files|js|favicon.ico)(.*)$" />
                    <action type="Rewrite" url="webroot/{R:1}{R:2}"
                      appendQueryString="false" />
                </rule>
                <rule name="Rewrite requested file/folder to index.php"
                  stopProcessing="true">
                    <match url="^(.*)$" ignoreCase="false" />
                    <action type="Rewrite" url="index.php"
                      appendQueryString="true" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>

:)

**Comment by justin222** [comment]
create a webconfig file with following content:
`<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="Exclude direct access to webroot/*"
                  stopProcessing="true">
                    <match url="^webroot/(.*)$" ignoreCase="false" />
                    <action type="None" />
                </rule>
                <rule name="Rewrite routed access to assets(img, css, files, js, favicon)"
                  stopProcessing="true">
                    <match url="^(img|css|files|js|favicon.ico)(.*)$" />
                    <action type="Rewrite" url="webroot/{R:1}{R:2}"
                      appendQueryString="false" />
                </rule>
                <rule name="Rewrite requested file/folder to index.php"
                  stopProcessing="true">
                    <match url="^(.*)$" ignoreCase="false" />
                    <action type="Rewrite" url="index.php"
                      appendQueryString="true" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>`
