### ISSUE TITLE
Not Found  The requested URL /wzusers/login was not found on this server.  Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

### ISSUE THREAD

**Issue by gopuvkm** [prashants/webzash#64]
Dear Sir

I am getting the above error on installation of webzash. Please advise. I have removed the security from controller, but still the issue is not resolved. I have hosted on a live server

Thanks

Gopan

**Comment by prashants** [comment]
https://github.com/prashants/webzash/wiki/Installation-Problems

**Comment by gopuvkm** [comment]
Dear Sir

I have tried this several time. Put still the problem persists

**Comment by gopuvkm** [comment]
i even upload .htaccess on root folder of webzash. 

<IfModule mod_rewrite.c>
   RewriteEngine on
   RewriteRule    ^$ app/webroot/    [L]
   RewriteRule    (.*) app/webroot/$1 [L]
</IfModule>

**Comment by prashants** [comment]
Check if apache rewrite mod is enabled

**Comment by gopuvkm** [comment]
How can i check the same

**Comment by prashants** [comment]
search on  google

**Comment by gopuvkm** [comment]
Tried but no able to resolve this. Please assist us

**Comment by aingelc12ell** [comment]
Here's worked for me: http://stackoverflow.com/questions/869092/how-to-enable-mod-rewrite-for-apache-2-2

**Comment by gopuvkm** [comment]
The issue is not yet resolved. Same error

**Comment by prashants** [comment]
can you try on local machine first and see if it works.

**Comment by prashants** [comment]
If the problem still persist then feel free to reopen the issue or create a new one.
