### ISSUE TITLE
Enhancement request for CoA

### ISSUE THREAD

**Issue by brandishwar** [prashants/webzash#65]
On the chart of accounts, I'd like to see the Groups showing the balance for all accounts within the group. This isn't necessary for the top-level accounts (Assets, Incomes, etc).

As an example, if I have a group under "Liabilities and Owners Equity" called "Credit cards" under which I have accounts for my credit/charge cards, having the "Credit cards" group showing the total "C/L Balance" for all accounts would plainly show the sum of my credit card balances.

**Comment by prashants** [comment]
This has been fixed in latest commit. Thanks.
