### ISSUE TITLE
Integration with other application developed in PHP and mySql

### ISSUE THREAD

**Issue by nadeem14375** [prashants/webzash#68]
hi all,

I am new, can I integrate to some other application developed in PHP and mySql? I want the entries made in that software directly inserted to webzash.

**Comment by snanshall** [comment]
At the point of setting up a new account on webzash you can specify the database you want to use. what i did was specify the database that the other application already uses then add a prefix so  there is no chance the tables created will conflict with the ones for my existing application. with the tables for webzash and my other application sitting on the same database i then modified the code in my application to update the websazh entryitems table with the entries made from my application.If you do it this way ,when you go to webzash those entries appear there.just take care to follow the same structure and use the ledgers set up on webzash
