### ISSUE TITLE
view all ledgers and ledger display

### ISSUE THREAD

**Issue by justin222** [prashants/webzash#69]
Hi, Prashants, 

1) Would like to ask you is it possible to view/print all ledgers at once instead of selecting 1 by 1 within the Report -> Ledger statement.

2) How to modify the display? For example i wish to view the ledger display without the it starting with "DR" "CR" then followed by my ledger code and ledger name. I want it to start straight away with ledger name.

**Comment by lofttroy** [comment]
First, this isn't great code. Second, it was written/hacked for v2.3, but the concept could be followed for v2.6.  But it does exactly what you've asked for in #1 above.

[ledgerstall.txt](https://github.com/prashants/webzash/files/477882/ledgerstall.txt)

**Comment by prashants** [comment]
/app/Plugin/Webzash/Controller/ReportsController.php -> ledgerstatement()
