### ISSUE TITLE
Database setup is not proper

### ISSUE THREAD

**Issue by sibidharan** [prashants/webzash#70]
This is what I am getting. How to configure the database?

Database Error
Error: SQLSTATE[HY000]: General error: 8 attempt to write a readonly database

SQL Query: UPDATE "main"."wzusers" SET "retry_count" = 0 WHERE "main"."wzusers"."id" = '1'

Notice: If you want to customize this error message, create app/View/Errors/pdo_error.ctp

Stack Trace
CORE/Cake/Model/Datasource/DboSource.php line 458 → PDOStatement->execute(array)
CORE/Cake/Model/Datasource/DboSource.php line 424 → DboSource->_execute(string, array)
CORE/Cake/Model/Datasource/DboSource.php line 2022 → DboSource->execute(string)
CORE/Cake/Model/Datasource/Database/Sqlite.php line 222 → DboSource->update(Wzuser, array, array, null)
CORE/Cake/Model/Model.php line 1838 → Sqlite->update(Wzuser, array, array)
CORE/Cake/Model/Model.php line 1681 → Model->save(array, array)
APP/Plugin/Webzash/Controller/WzusersController.php line 485 → Model->saveField(string, integer)
[internal function] → WzusersController->login()
CORE/Cake/Controller/Controller.php line 490 → ReflectionMethod->invokeArgs(WzusersController, array)
CORE/Cake/Routing/Dispatcher.php line 191 → Controller->invokeAction(CakeRequest)
CORE/Cake/Routing/Dispatcher.php line 165 → Dispatcher->_invoke(WzusersController, CakeRequest)
APP/webroot/index.php line 108 → Dispatcher->dispatch(CakeRequest, CakeResponse)

**Comment by chadwalt** [comment]
Solution : Make app/Plugin/Webzash/Database/webzash.sqlite writeable
