### ISSUE TITLE
Accounting Application stop working

### ISSUE THREAD

**Issue by danilogg** [prashants/webzash#72]
**I started using the application in May 2016 and like it very much.
Today August 17 want to continue with my work and the system gave me the following warnings in the login page: You can see them in the attached file screen01.png**

Warning (2): session_start(): open(/var/php_sessions/sess_d03f0563ac723ffeebfc2d4d91874950, O_RDWR) failed: No such file or directory (2) [CORE/Cake/Model/Datasource/CakeSession.php, line 661]

Warning (2): session_start(): Cannot send session cache limiter - headers already sent (output started at /hermes/bosnaweb16a/b165/nf.superkm/public_html/gravies/lib/Cake/Utility/Debugger.php:801) [CORE/Cake/Model/Datasource/CakeSession.php, line 661]

**and this 2 at the bottom**

Warning (2): Unknown: open(/var/php_sessions/sess_d03f0563ac723ffeebfc2d4d91874950, O_RDWR) failed: No such file or directory (2) [Unknown, line 0]

Warning (2): Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/php_sessions) [Unknown, line 0]

**After click the login button I received the following message. Please see attached file screen02.png
![screen01](https://cloud.githubusercontent.com/assets/21093165/17759369/9fd276d8-64c4-11e6-88a1-143b7ce553fb.PNG)
![screen02](https://cloud.githubusercontent.com/assets/21093165/17759368/9fd26058-64c4-11e6-9ca7-f1eff8dc5a63.PNG)

:**

Webzash
Errors
The request has been black-holed
Error: The requested address '/gravies/wzusers/login' was not found on this server.

Stack Trace
CORE/Cake/Controller/Component/SecurityComponent.php line 242 → SecurityComponent->blackHole(WzusersController, string)
[internal function] → SecurityComponent->startup(WzusersController)
CORE/Cake/Utility/ObjectCollection.php line 128 → call_user_func_array(array, array)
[internal function] → ObjectCollection->trigger(CakeEvent)
CORE/Cake/Event/CakeEventManager.php line 242 → call_user_func(array, CakeEvent)
CORE/Cake/Controller/Controller.php line 675 → CakeEventManager->dispatch(CakeEvent)
CORE/Cake/Routing/Dispatcher.php line 187 → Controller->startupProcess()
CORE/Cake/Routing/Dispatcher.php line 165 → Dispatcher->_invoke(WzusersController, CakeRequest)
APP/webroot/index.php line 108 → Dispatcher->dispatch(CakeRequest, CakeResponse)

**Any help will be very much appreciated.

Danilo**

**Comment by prashants** [comment]
It seems some issue with your web server setup. If the problem persists please reopen the issue. I am closing it for now.
