### ISSUE TITLE
Cannot use 'String' as class name as it is reserved

### ISSUE THREAD

**Issue by chadwalt** [prashants/webzash#73]
I  have downloaded the application and extracted it to xampp htdocs but am getting this error on opening it. Cannot use 'String' as class name as it is reserved
![screenshot from 2016-09-08 23-13-31](https://cloud.githubusercontent.com/assets/11385771/18365092/ea7fbf0e-7619-11e6-8f3b-6cf7a5df8227.png)

**Comment by prashants** [comment]
Can you use PHP 5 ? PHP 7 is not yet supported.

**Comment by prashants** [comment]
Latest version support PHP 7. Closing this issue.
