### ISSUE TITLE
Missing controller

### ISSUE THREAD

**Issue by lungu-catalin** [prashants/webzash#8]
Hi Prashants,
I have followed your instructions from http://webzash.org/develop and now I want to run the app but it seems like a file is missing.
![1](https://cloud.githubusercontent.com/assets/6849405/5789190/34d652aa-9e69-11e4-816c-61c77ff6959c.png)
Please help me to run the app.

Catalin

**Comment by prashants** [comment]
That guide is old. Use this

https://github.com/prashants/webzash/blob/master/README.txt

**Comment by prashants** [comment]
I have updated the guide on the website

**Comment by lungu-catalin** [comment]
Thank you. With the new guide I don't have the error but after press the Submit button on the configuration wizard I have another one.
![2](https://cloud.githubusercontent.com/assets/6849405/5791741/fe07ae3c-9ef3-11e4-9bb5-a181ee5318b1.png)

**Comment by lungu-catalin** [comment]
Finally it's working. I reinstalled the app.

Thanks.

**Comment by prashants** [comment]
for security reasons you will get the black hole error if you resubmit the same form or the timeout expires.
