### ISSUE TITLE
how to copy the "Entry" to be added to the program?

### ISSUE THREAD

**Issue by abbasgholia** [prashants/webzash#81]
hi
please help me?
regard
Abbasgholia

**Comment by prashants** [comment]
you want to duplicate a entry ?

**Comment by abbasgholia** [comment]
The picture attach


have the ability to copy entries.
 copies of the entries can be saved.
![21](https://cloud.githubusercontent.com/assets/16903097/20087573/edf3bd3a-a58e-11e6-8bbe-1a14e4876179.png)

**Comment by abbasgholia** [comment]
please help me!!

**Comment by prashants** [comment]
You will have to customize it by looking at the code. Its not that hard.

**Comment by abbasgholia** [comment]
i could not
if it is possible, please some help me

**Comment by abbasgholia** [comment]
is it possible for there tips?

**Comment by prashants** [comment]
I can do it but I will take some charge for it since it is specifically for you.

**Comment by abbasgholia** [comment]
but in my country can not afford.
how much does it cost?
the answer you very much

**Comment by abbasgholia** [comment]
create a duplicate entry registered.
there may be many similar entries
and some entries have hundreds of rows.
copy entries passed to the accountant can help in registration of new entries.
In all there are financial accounting software.
im a supporter of the country's largest accounting software and many ideas can be added in the application.
im programming with amateur cakephp and now I am reading this Framework.
im trying to build it if God wants to do
regard abbasgholia

**Comment by abbasgholia** [comment]
Excuse me, I ask too much
what is wrong with this code?
` function copy($entrytypeLabel = null , $id = null){
        
        $entryitem = $this->Entryitem->findByentry_id($id);
        $entry = $this->Entry->findById($id);
        unset($entry['Entry']['id'],$entryitem['Entryitem']['entry_id']);
		$this->Entry->create();
		$this->Entry->saveAll($entry);

    return $this->redirect(array('plugin' => 'webzash', 'controller' => 'entries', 'action' => 'index'));
    }`

**Comment by prashants** [comment]
Use the edit entry code, just dont set the entry number.

**Comment by prashants** [comment]
Or you could just copy the database rows for entries, entryitems. This will be really simple to implement.

**Comment by abbasgholia** [comment]
convenient for you.
I do not know framework cakephp :)
In this framework amateur am.
If the php maybe it was just now
thank you answer
Indians i love ;)

**Comment by prashants** [comment]
I will send you the code by this weekend.

**Comment by abbasgholia** [comment]
thank you so much

**Comment by prashants** [comment]
https://gist.github.com/prashants/5f2cce6979dcec4684bb4f363a11926c

**Comment by abbasgholia** [comment]
it came to my mind.
thank you for taking me.
regard abbasgholia
