### ISSUE TITLE
This is MySQL project, but database is in .sqlite file

### ISSUE THREAD

**Issue by goosehub** [prashants/webzash#83]
Perhaps I'm misunderstanding, but if this is a MySQL project, why is the default database connection in MasterConfig.php for sqlite, and the database file for import a .sqlite file. How does a user import the .sqlite database file into a MySQL database?

**Comment by goosehub** [comment]
I found the problem. The README does not mention you have to import the database as a step. MasterConfig is by default sqlite, but you can change that to MySQL, then go to app/Plugin/Webzash/Config/MasterChema.MySQL.sql and import that into the database. This should probably be in the README, right before "Thats it ! You are done :)"

**Comment by prashants** [comment]
There is one master database to store user info which is sqlite. Accounts database are in MySQL format.

https://github.com/prashants/webzash/wiki/MySQL-for-user-and-account-information

**Comment by goosehub** [comment]
I was able to get it working without sqlite.
