### ISSUE TITLE
Opening balance error across pagination

### ISSUE THREAD

**Issue by gojiraKi** [prashants/webzash#86]
Hi, the opening balance in ledger report are displaying wrong value. 
![error1pagination](https://cloud.githubusercontent.com/assets/20536079/21953735/5158ca18-da65-11e6-83ed-aa00e28949b0.png)
![error2pagination](https://cloud.githubusercontent.com/assets/20536079/21953738/56c4b3a4-da65-11e6-8783-b478a4d8608c.png)

**Comment by prashants** [comment]
which version of webzash are you using ?

**Comment by gojiraKi** [comment]
Version 2.5

**Comment by prashants** [comment]
Can you give me access to your setup ?

**Comment by prashants** [comment]
If possible can you send me entire page screenshot for all pages from 1 to 3 including the top summary

**Comment by gojiraKi** [comment]
Hi
How do i provide access to u
N i will send u the screenshot shortly

**Comment by prashants** [comment]
Email me details at pshah.mumbai at gmail.com

**Comment by gojiraKi** [comment]
Right now the project is not live and is hosted on localhost. I can send
you the code though

**Comment by prashants** [comment]
You can email me the MySQL dump

**Comment by gojiraKi** [comment]
[image: Inline image 1]
[image: Inline image 2]
[image: Inline image 3]

**Comment by prashants** [comment]
Images are not visible

**Comment by gojiraKi** [comment]
Here's the sql dump.

On Sat, Jan 14, 2017 at 3:42 PM, phalkishwor laipubam <disismynuid@gmail.com

**Comment by prashants** [comment]
Where ?

**Comment by gojiraKi** [comment]
![page1](https://cloud.githubusercontent.com/assets/20536079/21954176/464b1ef4-da70-11e6-8ac5-1af42a6aa02d.png)
![page2](https://cloud.githubusercontent.com/assets/20536079/21954177/499d4762-da70-11e6-9d6b-2ef5fc7d1f78.png)
![page3](https://cloud.githubusercontent.com/assets/20536079/21954180/4c8574e0-da70-11e6-8423-acf17eeda3c7.png)

**Comment by gojiraKi** [comment]
I'm sending again 
[lis.zip](https://github.com/prashants/webzash/files/705863/lis.zip)

**Comment by prashants** [comment]
Will check it. Thx

**Comment by prashants** [comment]
![screenshot from 2017-01-15 22-11-19](https://cloud.githubusercontent.com/assets/68140/21964300/98bb8a0c-db6f-11e6-8046-823837998dec.png)

Works fine on my end. Please update to latest version of webzash v2.6. Also it seems you have made lot of changes to the code base.

**Comment by prashants** [comment]
If you can come on teamviewer I can check out whats the problem.

**Comment by gojiraKi** [comment]
Hi, are you still online

**Comment by prashants** [comment]
yes

**Comment by gojiraKi** [comment]
Yeah! I guess some changes has been made. My senior was working on this project and ask me to check out this particular issue.

**Comment by prashants** [comment]
Can you try with keeping the database same and creating a new webzash setup and adding a account link to that database.

**Comment by gojiraKi** [comment]
I could try that. Should I come live on teamviewer now?

**Comment by prashants** [comment]
yeah

**Comment by gojiraKi** [comment]
My id 673 627 887

**Comment by prashants** [comment]
email me the password on pshah.mumbai @ gmail.com

**Comment by prashants** [comment]
teamviewer is not starting on my pc. its late night so will try tom.

**Comment by gojiraKi** [comment]
Hi! I've upgraded as you suggested and now it's working fine. I've a query though. What is the purpose or what is the field 'number' in the 'entries' table used for? It is not unique and that's why it is quite confusing.

**Comment by prashants** [comment]
It's entry number. It is user defined in the settings - entry type whether
user wants it unique. Uniqueness is handled by code.

**Comment by prashants** [comment]
Since the opening balance issue is solved I am closing this. If you have any other problems open a new issue.
