### ISSUE TITLE
Select-DropDown for Account with autocomplete?

### ISSUE THREAD

**Issue by marteserede** [prashants/webzash#9]
Hi,
when in Webzash I add an Entry one has to choose from a drop down menu the Account to which the entry shall be credited/debited.
I like to go though the form by hitting tab. Since the accounts are grouped, you can not easily choose the right one by just typing and selecting.
Therefore I think it would be great to implement something like this:
https://select2.github.io/examples.html
For the Account-Selection.
Or what do you think?

**Comment by prashants** [comment]
Good idea. Send a pull request and I will merge it.

**Comment by prashants** [comment]
Added in the latest commit.

How to update plugin

https://github.com/prashants/webzash/wiki/Webzash-update-plugin

Let me know if it works.

**Comment by marteserede** [comment]
Looks good and is already much better than the big list...
Unfortunately using the keyboard to tab through the form does not work, because when the dropdown-menu with select2 is focused and I type, nothing happens.
It seems like select2 simply does not work that way:
http://stackoverflow.com/questions/20989458/select2-open-dropdown-on-focus

**Comment by prashants** [comment]
Will try to fix it soon.

**Comment by prashants** [comment]
Try using the enter key and let me know if it works

**Comment by marteserede** [comment]
Yes, works perfectly. Thanks!

**Comment by prashants** [comment]
New version has been released which uses select2 :)

**Comment by agie0925** [comment]
Hello, I've installed webzash 2.5 just a moment. Really awesome! , But I found a problem when trying entry journal, I couldn't select legder options. It's disabled. How to enable this? Then I look at the online demo here => http://webzash.org/demo/webzash/entries/add/journal , I see the demo still use native select option (not select2 plugin) and it works. why?

**Comment by prashants** [comment]
you need non bank accounts in journal
