### ISSUE TITLE
Balance Sheet Options have "Start date" and "End date" but should only have "Date"

### ISSUE THREAD

**Issue by paulfeakins** [prashants/webzash#90]
Great software by the way, very clean and simple!

I noticed that the Balance Sheet has a "Start Date" and an "End Date" but actually "**the balance sheet is the only statement which applies to a single point in time** of a business' calendar year".
https://en.wikipedia.org/wiki/Balance_sheet

This should be changed so that there is only "Date" that can be selected.

**Comment by prashants** [comment]
Thanks ! Best way is to not select the start date.

**Comment by paulfeakins** [comment]
Ah good to know, thanks! 

Still, I think it would good to fix as this is a fundamental accounting principle and could cause confusion for users.

**Comment by prashants** [comment]
Fixed in latest release.
