### ISSUE TITLE
Profit & Loss Statement Totals Incorrect

### ISSUE THREAD

**Issue by paulfeakins** [prashants/webzash#91]
I've created a set of accounts as a test and added a couple of entries:

1. A client invoice at £1000+VAT 
2. An expense of £9+VAT

Now, generating a P&L for this period, I see 4 areas:

1. Gross Expenses
2. Gross Incomes
3. Net Expenses
4. Net Incomes

At the bottom of each section there is a grey bar that shows "Total":
http://www.antropy.co.uk/images/screenshots/8dadff71b1ff7811d0b1488.jpg

I would expect the Total under 1 to come to £9, but it shows as Dr £1000.00.
The Total for 2 seems correct.
Area 3 has a green "Net Profit" at £991, but area 3 is Net Expenses so the total should be £0.
Area 4 shows "Total Incomes" of 0 and a Total in the grey bar of £991. 

So it seems the P&L is a bit messed up?

**Comment by prashants** [comment]
Statements are correct. You need to interpret it differently. Both the Dr and Cr final total should be same on both sides hence its shown in this way.

**Comment by paulfeakins** [comment]
Ok, thank you for clarifying, I understand the presentation now. I am just trying to understand if this software will be suitable for our business. We currently use GnuCash and the presentation is a little different.
