### ISSUE TITLE
Can't install Webzash

### ISSUE THREAD

**Issue by furkansuv** [prashants/webzash#93]
Im trying to install webzash on my webhosting. I have given to this files and folders 777 permissions but the problem is not fixed yet.. anyone idea? Thanks!

Warning: _cake_core_ cache was unable to write 'cake_dev_de-de' to File cache in /opt/lampp/htdocs/demo/lib/Cake/Cache/Cache.php on line 322

Warning: /opt/lampp/htdocs/demo/app/tmp/cache/persistent/ is not writable in /opt/lampp/htdocs/demo/lib/Cake/Cache/Engine/FileEngine.php on line 385

Fatal error: Uncaught CacheException: Cache engine _cake_core_ is not properly configured. in /opt/lampp/htdocs/demo/lib/Cake/Cache/Cache.php:181 Stack trace: #0 /opt/lampp/htdocs/demo/lib/Cake/Cache/Cache.php(151): Cache::_buildEngine('_cake_core_') #1 /opt/lampp/htdocs/demo/app/Config/core.php(373): Cache::config('_cake_core_', Array) #2 /opt/lampp/htdocs/demo/lib/Cake/Core/Configure.php(72): include('/opt/lampp/htdo...') #3 /opt/lampp/htdocs/demo/lib/Cake/bootstrap.php(175): Configure::bootstrap(true) #4 /opt/lampp/htdocs/demo/app/webroot/index.php(94): include('/opt/lampp/htdo...') #5 /opt/lampp/htdocs/demo/index.php(41): require('/opt/lampp/htdo...') #6 {main} thrown in /opt/lampp/htdocs/demo/lib/Cake/Cache/Cache.php on line 181

**Comment by prashants** [comment]
Please check if permissions are being properly applied, sometimes even after setting the permissions, they are not actually applied to the files and folder.

You need to only give 755 permissions, anything more than that will be e security issue.
