### ISSUE TITLE
Webzash-v2.7 files corrupt?

### ISSUE THREAD

**Issue by Syenta** [prashants/webzash#94]
I have been trying for a few days to get Webzash-v2.7 to run on my system. Finally I gave up and downloaded Webzash-v2.6 and it worked first time.

With Webzash-v2.7 all I was unable to do was "http://localhost/webzash-v2.6/webzash" and it would return an 500 error, if I remember correctly.

Hope this helps

**Comment by prashants** [comment]
Some people reported errors with the 2.7 setup, but I am not able to pinpoint the exact reason for it.

What kind of setup are you using ?

**Comment by prashants** [comment]
Can you provide more details of the setup you are using.

**Comment by jacksumit** [comment]
I am also facing the same issue. I tried debugging and below are the findings so far.

Looks like php is facing issue with below line of code in webroot/index.php

if (!include 'Cake' . DS . 'bootstrap.php') {
		$failed = true;
	}

Error 500 do not happens if I Comment out these lines of codes and all the code after these lines. Error 500 reappears when above lines are Uncommented (while keeping all the code after these lines commented)

**Comment by prashants** [comment]
1. Are you using a clean setup  or you have updated just the plugin ?

2. Can you give me details of the setup you are using.

3. Whether the location of file is "app/webroot/index.php"

4. One thing you can try is enable the debug mode in app/Config/core.php

       Configure::write('debug', 2);

I have tested it on Linux with XAMPP with PHP 5 and 7 and I am not facing any issues.

**Comment by jacksumit** [comment]
It started working after setting Configure::write('debug', 2);

**Comment by prashants** [comment]
@jacksumit  So just by setting the debug parameter to 2 everything is working and no further changes are required ?

@Syenta can you please confirm whether it works on your end so that I can close this issue.

**Comment by jacksumit** [comment]
Yes, it started working just by changing debug parameter.

**Comment by prashants** [comment]
Everything is fixed in the new release. Download the latest version v2.7 from website. Incase if any other problems please reopen this issue.
