### ISSUE TITLE
Requested URL not found

### ISSUE THREAD

**Issue by karuppiah7890** [prashants/webzash#97]
I have PHP 5.5 and MariaDB 5.5 and I get the below error. But the URL gets redirected to " http://64.71.135.225/wzusers/login " properly, though I type " http://64.71.135.225 " only
"Not Found

The requested URL /wzusers/login was not found on this server."

**Comment by karuppiah7890** [comment]
But when I access http://64.71.135.225/app I get this 

![webzash](https://user-images.githubusercontent.com/12808424/30035844-de38af3e-91cb-11e7-9b4e-3bb1c69fae3c.png)

**Comment by beinafuushop** [comment]
Hello,

I have installation problem as well, Am trying to install the system in bluehost, Can some one please help me like what .sql file should i import? Also what else need to be changed?

**Comment by prashants** [comment]
@beinafuushop There is a video guide on how to install.

https://github.com/prashants/webzash/wiki/Installation-Problems

**Comment by karuppiah7890** [comment]
Thanks @prashants , I will check it out
